Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::prefix('zendesk')->group(function() {
//     Route::get('/', 'ZendeskController@index');
// });

Route::middleware(['auth'])->group(function () {
    Route::prefix('manage')->group(function() {
        Route::prefix('zendesk')->group(function() {
            Route::name('zendesk.')->group(function() {

                Route::get('dashboard', 'ZendeskController@index')->name('dashboard');

                Route::prefix('ticket')->group(function() {
                    Route::get('/', 'Admin\TicketController@index')->name('ticket.index');
                    Route::get('data', 'Admin\TicketController@indexData')->name('ticket.index.data');
                    Route::get('search', 'Admin\TicketController@search')->name('ticket.search');
                    Route::get('export/excel', 'Admin\TicketController@exportToExcel')->name('ticket.export.excel');

                    Route::get('search/test', 'Admin\TicketController@searchTest')->name('ticket.search.test');
                });

                Route::prefix('brand')->group(function() {
                    Route::get('/', 'Admin\BrandController@index')->name('brand.index');
                    Route::get('data', 'Admin\BrandController@indexData')->name('brand.index.data');
                    Route::get('sync', 'Admin\BrandController@sync')->name('brand.sync');
                });

            });
        });
    });
});

Entities/Brand.php
<?php

namespace Modules\Zendesk\Entities;

use App\Traits\Uuid as TraitsUuid;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Brand extends ZendeskModel
{
    use HasFactory, TraitsUuid, SoftDeletes;

    protected $table = ZendeskModel::DB_TABLE_PREFIX . 'brands';

    protected $fillable = [
        'brand_id',
        'name',
        'brand_url',
        'url',
        'subdomain',
        'has_help_center',
        'help_center_state',
        'active',
        'default',
        'logo',
        'ticket_form_ids',
        'host_mapping',
        'created_date',
        'updated_date',
        'deleted',
        'sync_by',
        'sync_at'
    ];

    public static function _getList()
    {
        return self::pluck('name', 'subdomain');
    }

}

Http/Controllers/Admin/BrandController.php
<?php

namespace Modules\Zendesk\Http\Controllers\Admin;

use Exception;
use Carbon\Carbon;
use GuzzleHttp\Client;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Zendesk\Entities\Brand;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Contracts\Support\Renderable;

class BrandController extends Controller
{
    protected $pageTitle;
    protected $client;
    protected $username, $token, $subdomain;

    public function __construct()
    {
        $this->pageTitle = 'Brands';
        $this->subdomain = config('zendesk-laravel.subdomain');
        $this->username = config('zendesk-laravel.username');
        $this->token = config('zendesk-laravel.token');
        $this->client   = new Client([
            'verify' => false
        ]);
    }
    
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        $params['pageTitle']    = $this->pageTitle;
        return view('zendesk::admin.brand.index', $params);
    }

    public function indexData(Request $request)
    {
        if($request->ajax()) {

            $data = new Brand();
            $data = $data->orderBy('default', 'desc')
                ->orderBy('updated_date', 'desc')
                ->get();

            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('name', function($row) {
                    $logo = !is_null($row->logo) ? '<img src="' . $row->logo . '" style="max-height: 30px; max-width: 40px" /> &nbsp;' : null;
                    $default = $row->default == 1 ? ' <span class="label bg-maroon-active"><i class="glyphicon glyphicon-pushpin"></i> default</span>' : null;
                    $name = $logo . $row->name . $default;
                    return $name;
                })
                ->addColumn('subdomain', function($row) {
                    $subdomain =  $row->subdomain . '<a href="' . $row->brand_url . '" target="_blank" title="click for detail"> <i class="fa fa-external-link"></i></a>';
                    return $subdomain;
                })
                ->addColumn('help_center', function($row) {
                    return __getHelpCenterStateLabel($row->help_center_state);
                })
                ->addColumn('active', function($row) {
                    return __getStateLabel($row->active);
                })
                ->addColumn('action', function($row) {
                    return null;
                })
                ->rawColumns([
                    'action', 'help_center', 'active', 'subdomain', 'name'
                ])
                ->make(true);
        }
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function sync()
    {
        try {
            $url        = 'https://' . $this->subdomain . '.zendesk.com/api/v2/brands.json';
            $request    = $this->client->get($url, [
                'headers' => [
                    'Authorization' => 'Basic ' . base64_encode($this->username . '/token:' . $this->token),
                    'Content-Type' => 'application/json'
                ],
            ]);
            $response   = $request->getBody()->getContents();
            $result = json_decode($response);

            if($result->count > 0) {

                foreach($result->brands as $row) {

                    $data['brand_id']   = $row->id;
                    $data['name']       = $row->name;
                    $data['brand_url']  = $row->brand_url;
                    $data['url']        = $row->url;
                    $data['subdomain']  = $row->subdomain;
                    $data['has_help_center']    = $row->has_help_center;
                    $data['help_center_state']  = $row->help_center_state;
                    $data['active']     = $row->active;
                    $data['default']    = $row->default;
                    $data['ticket_form_ids']    = implode(', ', $row->ticket_form_ids);
                    $data['created_date']       = dateFormatYmdHis($row->created_at);
                    $data['updated_date']       = dateFormatYmdHis($row->updated_at);
                    $data['deleted']            = $row->is_deleted;
                    $data['host_mapping']       = $row->host_mapping;

                    $data['logo']       = !is_null($row->logo) ? $row->logo->content_url : null;
                    $data['sync_by']    = Auth::user()->id;
                    $data['sync_at']    = Carbon::now();

                    $checkBrand = Brand::where('brand_id', $row->id)->first();
                    if($checkBrand) {
                        if($checkBrand->updated_at == dateFormatYmdHis($row->updated_at)) {
                            $checkBrand->update($data);
                        }
                    } else {
                        Brand::create($data);
                    }
                }
            }

            return redirect()->route('zendesk.brand.index')
                ->with('success', trans('message.success_save'));
        } catch(Exception $e) {
            return redirect(route('zendesk.brand.index'))
				->with('error', trans('message.error_save'));
        }
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        return view('zendesk::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        return view('zendesk::edit');
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {
        //
    }
}

Resources/views/admin/brand/index.blade.php
@extends('zendesk::layouts.master')

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title"></h3>
                    <div class="box-tools pull-right">
                        @can('zendesk-brand-sync')
                            <a class="btn btn-sm btn-info" href="{!! route('zendesk.brand.sync') !!}">
                                <i class="fa fa-refresh"></i> Sync
                            </a>
                        @endcan
                    </div>
                </div>
                <div class="box-body" style="min-height: 520px">
                    <div class="row">
                        <div class="col-md-12">
                            <table id="grid-tickets" class="table table-bordered table-striped table-responsive" style="width:100%;">
                                <thead>
                                    <tr>
                                        <th class="text-center" style="width: 2%; vertical-align: middle">#</th>
                                        <th class="text-center" style="width: 2%; vertical-align: middle">Brand ID</th>
                                        <th class="text-center" style="vertical-align: middle">Brand Name</th>
                                        <th class="text-center" style="width: 12%; vertical-align: middle">Subdomain</th>
                                        <th class="text-center" style="width: 10%; vertical-align: middle">Ticket<br>Form ID</th>
                                        <th class="text-center" style="width: 7%; vertical-align: middle">Help Center</th>
                                        <th class="text-center" style="width: 7%; vertical-align: middle">Status</th>
                                        <th class="text-center" style="width: 5%; vertical-align: middle">Created</th>
                                        <th class="text-center" style="width: 5%; vertical-align: middle">Updated</th>
                                        {{-- <th class="text-center" style="width: 5%; vertical-align: middle">
                                            <i class="fa fa-navicon"></i>
                                        </th> --}}
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript">
        $(document).ready(function() {
            var table = $('#grid-tickets').DataTable({
                processing: true,
                serverSide: true,
                responsive: false,
                PaginationType: "two_button",
                paginate:true,
                deferRender: true,
                keys: false,
                dom: '<"row"<"col-md-4"l><"col-md-4 text-center"B><"col-md-4"f>>' + 'rtip',
                buttons: [
                    {
                        text: '<i class="fa fa-refresh"></i> Refresh',
                        className: "btn-sm",
                        action: function(e, dt, node, config) {
                            dt.ajax.reload(null, false);
                        }
                    },
                ],
                ajax: { 
                    url: "{!! route('zendesk.brand.index.data') !!}",
                    pages: 100,
                },
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex', className: "small text-center", orderable: false, searchable: false},
                    {data: 'brand_id', name: 'brand_id', className: "small text-center", orderable: false},
                    {data: 'name', name: 'name', className: "small", orderable: false},
                    {data: 'subdomain', name: 'subdomain', className: "small", orderable: false},
                    {data: 'ticket_form_ids', name: 'ticket_form_ids', className: "small", orderable: false},
                    {data: 'help_center', name: 'help_center', className: "small", orderable: false},
                    {data: 'active', name: 'active', className: "small", orderable: false},
                    {data: 'created_date', name: 'created_date', className: "small text-right"},
                    {data: 'updated_date', name: 'updated_date', className: "small text-right"},
                    // {data: 'action', name: 'action', className: "small text-center", orderable: false, searchable: false},
                ],
                columnDefs: [
                    {targets: 7, render: $.fn.dataTable.render.moment('YYYY-MM-DD HH:mm:ss', 'DD-MM-YYYY HH:mm:ss' )},
                    {targets: 8, render: $.fn.dataTable.render.moment('YYYY-MM-DD HH:mm:ss', 'DD-MM-YYYY HH:mm:ss' )},
                ],
                // order: [
                    // [8, 'desc']
                // ],
                language: {
                    processing: "<p class='text-center'>Loading...</p>"
                },
            });
        });
    </script>
@endsection