Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::prefix('zendesk')->group(function() {
//     Route::get('/', 'ZendeskController@index');
// });

Route::middleware(['auth'])->group(function () {
    Route::prefix('manage')->group(function() {
        Route::prefix('zendesk')->group(function() {
            Route::name('zendesk.')->group(function() {

                Route::get('dashboard', 'ZendeskController@index')->name('dashboard');

                Route::prefix('ticket')->group(function() {
                    Route::get('/', 'Admin\TicketController@index')->name('ticket.index');
                    Route::get('data', 'Admin\TicketController@indexData')->name('ticket.index.data');
                    Route::get('search', 'Admin\TicketController@search')->name('ticket.search');
                    Route::get('export/excel', 'Admin\TicketController@exportToExcel')->name('ticket.export.excel');

                    Route::get('search/test', 'Admin\TicketController@searchTest')->name('ticket.search.test');
                });

                Route::prefix('brand')->group(function() {
                    Route::get('/', 'Admin\BrandController@index')->name('brand.index');
                    Route::get('data', 'Admin\BrandController@indexData')->name('brand.index.data');
                    Route::get('sync', 'Admin\BrandController@sync')->name('brand.sync');
                });

            });
        });
    });
});

Resources/views/admin/shared/sidebar.blade.php
@can('zendesk')
<li class="treeview @if($adminActiveMenu == 'zendesk') active @endif">
    <a href="#">
        <i class="fa fa-ticket"></i>
        <span>Zendesk</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
            <span class="label label-danger pull-right">
                New
            </span>
        </span>
    </a>
    <ul class="treeview-menu">
        {{-- @can('zendesk-dashboard-read')
        <li class="@if($adminActiveSubMenu == 'dashboard') active @endif">
            <a href="{!! route('zendesk.dashboard') !!}">
                <i class="fa fa-circle-o"></i> Dashboard
                <span class="pull-right-container"></span>
            </a>
        </li>
        @endcan --}}
        @can('zendesk-ticket')
            <li class="@if($adminActiveSubMenu == 'ticket') active @endif">
                <a href="#"><i class="fa fa-circle-o"></i> Tickets
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    @can('zendesk-ticket-read')
                        <li class="@if($adminActiveSubMenu == 'ticket' && $urlSegment4 == '') active @endif">
                            <a href="{!! route('zendesk.ticket.index') !!}">
                                <i class="fa fa-circle-o"></i> Tickets List
                                <span class="pull-right-container"></span>
                            </a>
                        </li>
                    @endcan
                </ul>
            </li>
            @can('zendesk-brand-read')
                <li class="@if($adminActiveSubMenu == 'brand' && $urlSegment4 == '') active @endif">
                    <a href="{!! route('zendesk.brand.index') !!}">
                        <i class="fa fa-circle-o"></i> Brands
                        <span class="pull-right-container"></span>
                    </a>
                </li>
            @endcan
        @endcan
        
    </ul>
</li>
@endcan