Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::prefix('zendesk')->group(function() {
//     Route::get('/', 'ZendeskController@index');
// });

Route::middleware(['auth'])->group(function () {
    Route::prefix('manage')->group(function() {
        Route::prefix('zendesk')->group(function() {
            Route::name('zendesk.')->group(function() {

                Route::get('dashboard', 'ZendeskController@index')->name('dashboard');

                Route::prefix('ticket')->group(function() {
                    Route::get('/', 'Admin\TicketController@index')->name('ticket.index');
                    Route::get('data', 'Admin\TicketController@indexData')->name('ticket.index.data');
                    Route::get('search', 'Admin\TicketController@search')->name('ticket.search');
                    Route::get('export/excel', 'Admin\TicketController@exportToExcel')->name('ticket.export.excel');

                    Route::get('search/test', 'Admin\TicketController@searchTest')->name('ticket.search.test');
                });

                Route::prefix('brand')->group(function() {
                    Route::get('/', 'Admin\BrandController@index')->name('brand.index');
                    Route::get('data', 'Admin\BrandController@indexData')->name('brand.index.data');
                    Route::get('sync', 'Admin\BrandController@sync')->name('brand.sync');
                });

            });
        });
    });
});

Http/Controllers/Admin/TicketController.php
<?php

namespace Modules\Zendesk\Http\Controllers\Admin;

use GuzzleHttp\Client;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Zendesk\Entities\Brand;
use Maatwebsite\Excel\Facades\Excel;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Contracts\Support\Renderable;
use Modules\Zendesk\Exports\TicketExportToExcel;

class TicketController extends Controller
{

    protected $pageTitle;
    protected $client;
    protected $username, $token, $subdomain;

    public function __construct()
    {
        $this->pageTitle = 'Ticket';
        $this->subdomain = config('zendesk-laravel.subdomain');
        $this->username = config('zendesk-laravel.username');
        $this->token = config('zendesk-laravel.token');
        $this->client   = new Client([
            'verify' => false
        ]);
    }

    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        $params['pageTitle']    = $this->pageTitle;
        $params['brand']        = Brand::_getList();
        return view('zendesk::admin.ticket.index', $params);
    }

    public function indexData(Request $request)
    {
        if($request->ajax()) {

            $data = $this->search($request)->results;

            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('description', function($row) {
                    $str = '------------------';
                    $desc = $row->description;
                    if(str_contains($desc, $str)) {
                        $desc = strstr($desc, '------------------', true);
                    }
                    return $desc;
                })
                ->addColumn('requester_email', function($row) {
                    // $requester = \__getUserDetail($row->requester_id)->email;
                    $requester = $row->requester_id['email'];
                    return $requester;
                })
                ->addColumn('channel', function($row) {
                    return $row->via->channel;
                })
                ->addColumn('action', function($row) {
                    return null;
                })
                ->rawColumns([
                    'action', 'channel', 'requester_email'
                ])
                ->make(true);
        }
    }

    public function search($req)
    {
        $query = 'type:ticket ';
        if(isset($req->brand)) {
            $query = $query . ' brand:' . $req->brand;
        }
        $url        = 'https://' . $this->subdomain . '.zendesk.com/api/v2/search.json';
        $request    = $this->client->get($url, [
            'headers' => [
                'Authorization' => 'Basic ' . base64_encode($this->username . '/token:' . $this->token),
                'Content-Type' => 'application/json'
            ],
            'query' => [
                'query' => $query,
                'sort_by' => 'created_at',
                'sort_order' => 'desc'
            ]
        ]);
        $response   = $request->getBody()->getContents();
        $result = json_decode($response);
        return $result;
    }

    public function exportToExcel()
    {
        
        $data = $this->search()->results;

        return Excel::download(new TicketExportToExcel($data), 'ticket_'.date('Y-m-d').'.xlsx');
        
    }

    public function searchTest()
    {
        $url        = 'https://' . $this->subdomain . '.zendesk.com/api/v2/search.json';
        $request    = $this->client->get($url, [
            'headers' => [
                'Authorization' => 'Basic ' . base64_encode($this->username . '/token:' . $this->token),
                'Content-Type' => 'application/json'
            ],
            'query' => [
                'query' => 'type:ticket created>='. date('Y-m-d') .' brand:Kedaireka',
                'sort_by' => 'created_at',
                'sort_order' => 'desc',
                'include' => 'tickets(users)',
            ]
        ]);
        $response   = $request->getBody()->getContents();
        $result = json_decode($response);

        // foreach($result->results as $row) {
        //     // dd($row->via);
        //     foreach ($row->fields as $item) {
        //         dd($item->id);
        //     }
        // }
        dd($result->results);
        return $result;
    }

}

Resources/views/admin/ticket/index.blade.php
@extends('zendesk::layouts.master')

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title"></h3>
                    <div class="box-tools pull-right">
                        @can('zendesk-ticket-export')
                            <a class="btn btn-sm btn-success" href="{!! route('zendesk.ticket.export.excel') !!}">
                                <i class="fa fa-file-excel-o"></i> Export to Excel
                            </a>
                        @endcan
                    </div>
                </div>
                <div class="box-body" style="min-height: 520px">
                    <div class="row">
                        <div class="col-md-6"></div>
                        <div class="col-md-6">
                            <div class="row">
                                <div class="col-md-4 col-xs-6">
                                    <div class="form-group">
                                        <label for="start_date" class="small">Brand</label>
                                        <div class="input-group date">
                                            {!! Form::select('brand', $brand, 'kedaireka', [ 'class' => 'form-control input-sm', 'id' => 'brand']) !!}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4 col-xs-6">
                                    <div class="form-group">
                                        <label for="button" class="small"></label>
                                        <div class="input-group">
                                            <button class="btn btn-sm btn-success" style="margin-top: 4.5px" id="btn_search">
                                                <i class="fa fa-search"></i> Cari
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-12">
                            <table id="grid-tickets" class="table table-bordered table-striped" style="width:100%;">
                                <thead>
                                    <tr>
                                        <th class="text-center" style="width: 2%; vertical-align: middle">#</th>
                                        <th class="text-center" style="width: 2%; vertical-align: middle">Ticket ID</th>
                                        <th class="text-center" style="width: 15%; vertical-align: middle">Subject</th>
                                        <th class="text-center" style="vertical-align: middle">Description</th>
                                        <th class="text-center" style="width: 10%; vertical-align: middle">Requester Email</th>
                                        <th class="text-center" style="width: 10%; vertical-align: middle">Channel</th>
                                        <th class="text-center" style="width: 10%; vertical-align: middle">Status</th>
                                        <th class="text-center" style="width: 5%; vertical-align: middle">Created</th>
                                        <th class="text-center" style="width: 5%; vertical-align: middle">Updated</th>
                                        <th class="text-center" style="width: 5%; vertical-align: middle">
                                            <i class="fa fa-navicon"></i>
                                        </th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript">
        $(document).ready(function() {
            var brand = $('#brand');
            var btnSearch = $('#btn_search');

            var table = $('#grid-tickets').DataTable({
                processing: true,
                serverSide: true,
                responsive: false,
                PaginationType: "two_button",
                paging:true,
                retrieve: true,
                deferRender: true,
                keys: false,
                stateSave: true,
                dom: '<"row"<"col-md-4"l><"col-md-4 text-center"B><"col-md-4"f>>' + 'rtip',
                buttons: [
                    {
                        text: '<i class="fa fa-refresh"></i> Refresh',
                        className: "btn-sm",
                        action: function(e, dt, node, config) {
                            dt.ajax.reload(null, false);
                        }
                    },
                ],
                ajax: { 
                    url: "{!! route('zendesk.ticket.index.data') !!}",
                    data: function(d) {
                        d.brand = brand.val()
                    },
                },
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex', className: "small", orderable: false, searchable: false},
                    {data: 'id', name: 'id', className: "small", orderable: false},
                    {data: 'subject', name: 'subject', className: "small", orderable: false},
                    {data: 'description', name: 'description', className: "small", orderable: false},
                    {data: 'requester_email', name: 'requester_email', className: "small", orderable: false},
                    {data: 'channel', name: 'channel', className: "small", orderable: false},
                    {data: 'status', name: 'status', className: "small", orderable: false},
                    {data: 'created_at', name: 'created_at', className: "small text-right"},
                    {data: 'updated_at', name: 'updated_at', className: "small text-right"},
                    {data: 'action', name: 'action', className: "small text-center", orderable: false, searchable: false},
                ],
                columnDefs: [
                    {targets: 7, render: $.fn.dataTable.render.moment('YYYY-MM-DDTHH:mm:ssZ', 'DD-MM-YYYY HH:mm:ss' )},
                    {targets: 8, render: $.fn.dataTable.render.moment('YYYY-MM-DDTHH:mm:ssZ', 'DD-MM-YYYY HH:mm:ss' )},
                ],
                order: [
                    [8, 'desc']
                ],
                language: {
                    processing: "<p class='text-center'>Loading...</p>"
                },
            });

            btnSearch.on('click', function(e) {
                e.preventDefault();
                getData();
            });

            function getData() {
                $.ajax({
                    url: "{!! route('zendesk.ticket.index.data') !!}",
                    type: "GET",
                    data: {
                        brand: brand.val(),
                    },
                    success: function(data) {
                        table.ajax.reload();
                    }
                });
            }
        });
    </script>
@endsection